name: Semantic Pull Request

on:
  pull_request:
    branches: master
    types: [opened, reopened, edited, synchronize]

jobs:
  semantic-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ecotricity/semantic-pull-request-action
          ref: v1.0.6
          token: ${{ secrets.DEVTEAM_GITHUB_TOKEN }}
      - uses: ./
